# Generated by Django 3.2.7 on 2026-03-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
