# Generated by Django 3.2.7 on 2026-04-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_order_custom_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_playlist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subscription_plan',
        ),
    ]
