# Generated by Django 3.2.7 on 2026-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20260402_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_installments',
            field=models.IntegerField(default=1),
        ),
    ]
